In [48]:
import requests
import pandas as pd

url = "https://free-nba.p.rapidapi.com/players"

querystring = {"page": "0", "per_page": "25"}

headers = {
    "X-RapidAPI-Key": "12d4c64124mshfbf72eb6ce24e35p183d15jsn354ab98aca9e",
    "X-RapidAPI-Host": "free-nba.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Convert JSON response to DataFrame
    data = response.json()
    df = pd.DataFrame(data["data"])
else:
    # Print the error status code and text
    print(f"Error: {response.status_code} - {response.text}")

In [49]:
df

,id,first_name,height_feet,height_inches,last_name,position,team,weight_pounds
0,149,Keenan,NaN,NaN,Evans,G,"{'id': 9, 'abbreviation': 'DET', 'city': 'Detr...",NaN
1,382,Billy,NaN,NaN,Preston,F,"{'id': 6, 'abbreviation': 'CLE', 'city': 'Clev...",NaN
2,448,Gary,NaN,NaN,Trent Jr.,G,"{'id': 25, 'abbreviation': 'POR', 'city': 'Por...",NaN
3,46391370,Jake,NaN,NaN,Carter,,"{'id': 50, 'abbreviation': 'DN', 'city': '', '...",NaN
4,2144,Rakeem,NaN,NaN,Christmas,,"{'id': 12, 'abbreviation': 'IND', 'city': 'Ind...",NaN
5,46391383,Bill,NaN,NaN,Closs,,"{'id': 10, 'abbreviation': 'GSW', 'city': 'Gol...",NaN
6,2714,Kent,NaN,NaN,Edelin,,"{'id': 12, 'abbreviation': 'IND', 'city': 'Ind...",NaN
7,46390214,Don,NaN,NaN,Eliason,,"{'id': 2, 'abbreviation': 'BOS', 'city': 'Bost...",NaN
8,46390206,Gorham,NaN,NaN,Getchell,,"{'id': 44, 'abbreviation': 'PIT', 'city': '', ...",NaN
9,46404351,Gary,NaN,NaN,Gregor,,"{'id': 25, 'abbreviation': 'POR', 'city': 'Por...",NaN
10,46393997,Jim,NaN,NaN,Holstein,,"{'id': 14, 'abbreviation': 'LAL', 'city': 'Los...",NaN
11,1703,Mile,NaN,NaN,Ilic,,"{'id': 3, 'abbreviation': 'BKN', 'city': 'Broo...",NaN
12,2305,Abdul,NaN,NaN,Jeelani,,"{'id': 25, 'abbreviation': 'POR', 'city': 'Por...",NaN
13,56677845,Colby,NaN,NaN,Jones,G,"{'id': 26, 'abbreviation': 'SAC', 'city': 'Sac...",NaN
14,46408537,Steve,NaN,NaN,Jones,,"{'id': 25, 'abbreviation': 'POR', 'city': 'Por...",NaN
15,38017692,Malaki,NaN,NaN,Branham,F,"{'id': 27, 'abbreviation': 'SAS', 'city': 'San...",NaN
16,1847,Jon,NaN,NaN,Brockman,,"{'id': 17, 'abbreviation': 'MIL', 'city': 'Mil...",NaN
17,38017702,Kennedy,NaN,NaN,Chandler,G,"{'id': 15, 'abbreviation': 'MEM', 'city': 'Mem...",NaN
18,915,Yinka,NaN,NaN,Dare,,"{'id': 3, 'abbreviation': 'BKN', 'city': 'Broo...",NaN
19,46408533,Rod,NaN,NaN,Derline,,"{'id': 21, 'abbreviation': 'OKC', 'city': 'Okl...",NaN
20,2830,Terry,NaN,NaN,Dozier,,"{'id': 4, 'abbreviation': 'CHA', 'city': 'Char...",NaN
21,2290,John,NaN,NaN,Drew,,"{'id': 1, 'abbreviation': 'ATL', 'city': 'Atla...",NaN
22,46405958,Ken,NaN,NaN,Durrett,,"{'id': 26, 'abbreviation': 'SAC', 'city': 'Sac...",NaN
23,141,Trevon,6.0,2.0,Duval,G,"{'id': 17, 'abbreviation': 'MIL', 'city': 'Mil...",189.0
24,1670,Jordan,NaN,NaN,Farmar,,"{'id': 14, 'abbreviation': 'LAL', 'city': 'Los...",NaN

In [50]:
df['team']
for i in df['team']:
  print(i)

{'id': 9, 'abbreviation': 'DET', 'city': 'Detroit', 'conference': 'East', 'division': 'Central', 'full_name': 'Detroit Pistons', 'name': 'Pistons'}
{'id': 6, 'abbreviation': 'CLE', 'city': 'Cleveland', 'conference': 'East', 'division': 'Central', 'full_name': 'Cleveland Cavaliers', 'name': 'Cavaliers'}
{'id': 25, 'abbreviation': 'POR', 'city': 'Portland', 'conference': 'West', 'division': 'Northwest', 'full_name': 'Portland Trail Blazers', 'name': 'Trail Blazers'}
{'id': 50, 'abbreviation': 'DN', 'city': '', 'conference': '    ', 'division': '', 'full_name': 'Denver Nuggets', 'name': 'Denver Nuggets'}
{'id': 12, 'abbreviation': 'IND', 'city': 'Indiana', 'conference': 'East', 'division': 'Central', 'full_name': 'Indiana Pacers', 'name': 'Pacers'}
{'id': 10, 'abbreviation': 'GSW', 'city': 'Golden State', 'conference': 'West', 'division': 'Pacific', 'full_name': 'Golden State Warriors', 'name': 'Warriors'}
{'id': 12, 'abbreviation': 'IND', 'city': 'Indiana', 'conference': 'East', 'division': 'Central', 'full_name': 'Indiana Pacers', 'name': 'Pacers'}
{'id': 2, 'abbreviation': 'BOS', 'city': 'Boston', 'conference': 'East', 'division': 'Atlantic', 'full_name': 'Boston Celtics', 'name': 'Celtics'}
{'id': 44, 'abbreviation': 'PIT', 'city': '', 'conference': '    ', 'division': '', 'full_name': 'Pittsburgh Ironmen', 'name': 'Pittsburgh Ironmen'}
{'id': 25, 'abbreviation': 'POR', 'city': 'Portland', 'conference': 'West', 'division': 'Northwest', 'full_name': 'Portland Trail Blazers', 'name': 'Trail Blazers'}
{'id': 14, 'abbreviation': 'LAL', 'city': 'Los Angeles', 'conference': 'West', 'division': 'Pacific', 'full_name': 'Los Angeles Lakers', 'name': 'Lakers'}
{'id': 3, 'abbreviation': 'BKN', 'city': 'Brooklyn', 'conference': 'East', 'division': 'Atlantic', 'full_name': 'Brooklyn Nets', 'name': 'Nets'}
{'id': 25, 'abbreviation': 'POR', 'city': 'Portland', 'conference': 'West', 'division': 'Northwest', 'full_name': 'Portland Trail Blazers', 'name': 'Trail Blazers'}
{'id': 26, 'abbreviation': 'SAC', 'city': 'Sacramento', 'conference': 'West', 'division': 'Pacific', 'full_name': 'Sacramento Kings', 'name': 'Kings'}
{'id': 25, 'abbreviation': 'POR', 'city': 'Portland', 'conference': 'West', 'division': 'Northwest', 'full_name': 'Portland Trail Blazers', 'name': 'Trail Blazers'}
{'id': 27, 'abbreviation': 'SAS', 'city': 'San Antonio', 'conference': 'West', 'division': 'Southwest', 'full_name': 'San Antonio Spurs', 'name': 'Spurs'}
{'id': 17, 'abbreviation': 'MIL', 'city': 'Milwaukee', 'conference': 'East', 'division': 'Central', 'full_name': 'Milwaukee Bucks', 'name': 'Bucks'}
{'id': 15, 'abbreviation': 'MEM', 'city': 'Memphis', 'conference': 'West', 'division': 'Southwest', 'full_name': 'Memphis Grizzlies', 'name': 'Grizzlies'}
{'id': 3, 'abbreviation': 'BKN', 'city': 'Brooklyn', 'conference': 'East', 'division': 'Atlantic', 'full_name': 'Brooklyn Nets', 'name': 'Nets'}
{'id': 21, 'abbreviation': 'OKC', 'city': 'Oklahoma City', 'conference': 'West', 'division': 'Northwest', 'full_name': 'Oklahoma City Thunder', 'name': 'Thunder'}
{'id': 4, 'abbreviation': 'CHA', 'city': 'Charlotte', 'conference': 'East', 'division': 'Southeast', 'full_name': 'Charlotte Hornets', 'name': 'Hornets'}
{'id': 1, 'abbreviation': 'ATL', 'city': 'Atlanta', 'conference': 'East', 'division': 'Southeast', 'full_name': 'Atlanta Hawks', 'name': 'Hawks'}
{'id': 26, 'abbreviation': 'SAC', 'city': 'Sacramento', 'conference': 'West', 'division': 'Pacific', 'full_name': 'Sacramento Kings', 'name': 'Kings'}
{'id': 17, 'abbreviation': 'MIL', 'city': 'Milwaukee', 'conference': 'East', 'division': 'Central', 'full_name': 'Milwaukee Bucks', 'name': 'Bucks'}
{'id': 14, 'abbreviation': 'LAL', 'city': 'Los Angeles', 'conference': 'West', 'division': 'Pacific', 'full_name': 'Los Angeles Lakers', 'name': 'Lakers'}

In [51]:
data['data']

[{'id': 149,
  'first_name': 'Keenan',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Evans',
  'position': 'G',
  'team': {'id': 9,
   'abbreviation': 'DET',
   'city': 'Detroit',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Detroit Pistons',
   'name': 'Pistons'},
  'weight_pounds': None},
 {'id': 382,
  'first_name': 'Billy',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Preston',
  'position': 'F',
  'team': {'id': 6,
   'abbreviation': 'CLE',
   'city': 'Cleveland',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Cleveland Cavaliers',
   'name': 'Cavaliers'},
  'weight_pounds': None},
 {'id': 448,
  'first_name': 'Gary',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Trent Jr.',
  'position': 'G',
  'team': {'id': 25,
   'abbreviation': 'POR',
   'city': 'Portland',
   'conference': 'West',
   'division': 'Northwest',
   'full_name': 'Portland Trail Blazers',
   'name': 'Trail Blazers'},
  'weight_pounds': None},
 {'id': 46391370,
  'first_name': 'Jake',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Carter',
  'position': '',
  'team': {'id': 50,
   'abbreviation': 'DN',
   'city': '',
   'conference': '    ',
   'division': '',
   'full_name': 'Denver Nuggets',
   'name': 'Denver Nuggets'},
  'weight_pounds': None},
 {'id': 2144,
  'first_name': 'Rakeem',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Christmas',
  'position': '',
  'team': {'id': 12,
   'abbreviation': 'IND',
   'city': 'Indiana',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Indiana Pacers',
   'name': 'Pacers'},
  'weight_pounds': None},
 {'id': 46391383,
  'first_name': 'Bill',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Closs',
  'position': '',
  'team': {'id': 10,
   'abbreviation': 'GSW',
   'city': 'Golden State',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'Golden State Warriors',
   'name': 'Warriors'},
  'weight_pounds': None},
 {'id': 2714,
  'first_name': 'Kent',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Edelin',
  'position': '',
  'team': {'id': 12,
   'abbreviation': 'IND',
   'city': 'Indiana',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Indiana Pacers',
   'name': 'Pacers'},
  'weight_pounds': None},
 {'id': 46390214,
  'first_name': 'Don',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Eliason',
  'position': '',
  'team': {'id': 2,
   'abbreviation': 'BOS',
   'city': 'Boston',
   'conference': 'East',
   'division': 'Atlantic',
   'full_name': 'Boston Celtics',
   'name': 'Celtics'},
  'weight_pounds': None},
 {'id': 46390206,
  'first_name': 'Gorham',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Getchell',
  'position': '',
  'team': {'id': 44,
   'abbreviation': 'PIT',
   'city': '',
   'conference': '    ',
   'division': '',
   'full_name': 'Pittsburgh Ironmen',
   'name': 'Pittsburgh Ironmen'},
  'weight_pounds': None},
 {'id': 46404351,
  'first_name': 'Gary',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Gregor',
  'position': '',
  'team': {'id': 25,
   'abbreviation': 'POR',
   'city': 'Portland',
   'conference': 'West',
   'division': 'Northwest',
   'full_name': 'Portland Trail Blazers',
   'name': 'Trail Blazers'},
  'weight_pounds': None},
 {'id': 46393997,
  'first_name': 'Jim',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Holstein',
  'position': '',
  'team': {'id': 14,
   'abbreviation': 'LAL',
   'city': 'Los Angeles',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'Los Angeles Lakers',
   'name': 'Lakers'},
  'weight_pounds': None},
 {'id': 1703,
  'first_name': 'Mile',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Ilic',
  'position': '',
  'team': {'id': 3,
   'abbreviation': 'BKN',
   'city': 'Brooklyn',
   'conference': 'East',
   'division': 'Atlantic',
   'full_name': 'Brooklyn Nets',
   'name': 'Nets'},
  'weight_pounds': None},
 {'id': 2305,
  'first_name': 'Abdul',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Jeelani',
  'position': '',
  'team': {'id': 25,
   'abbreviation': 'POR',
   'city': 'Portland',
   'conference': 'West',
   'division': 'Northwest',
   'full_name': 'Portland Trail Blazers',
   'name': 'Trail Blazers'},
  'weight_pounds': None},
 {'id': 56677845,
  'first_name': 'Colby',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Jones',
  'position': 'G',
  'team': {'id': 26,
   'abbreviation': 'SAC',
   'city': 'Sacramento',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'Sacramento Kings',
   'name': 'Kings'},
  'weight_pounds': None},
 {'id': 46408537,
  'first_name': 'Steve',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Jones',
  'position': '',
  'team': {'id': 25,
   'abbreviation': 'POR',
   'city': 'Portland',
   'conference': 'West',
   'division': 'Northwest',
   'full_name': 'Portland Trail Blazers',
   'name': 'Trail Blazers'},
  'weight_pounds': None},
 {'id': 38017692,
  'first_name': 'Malaki',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Branham',
  'position': 'F',
  'team': {'id': 27,
   'abbreviation': 'SAS',
   'city': 'San Antonio',
   'conference': 'West',
   'division': 'Southwest',
   'full_name': 'San Antonio Spurs',
   'name': 'Spurs'},
  'weight_pounds': None},
 {'id': 1847,
  'first_name': 'Jon',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Brockman',
  'position': '',
  'team': {'id': 17,
   'abbreviation': 'MIL',
   'city': 'Milwaukee',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Milwaukee Bucks',
   'name': 'Bucks'},
  'weight_pounds': None},
 {'id': 38017702,
  'first_name': 'Kennedy',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Chandler',
  'position': 'G',
  'team': {'id': 15,
   'abbreviation': 'MEM',
   'city': 'Memphis',
   'conference': 'West',
   'division': 'Southwest',
   'full_name': 'Memphis Grizzlies',
   'name': 'Grizzlies'},
  'weight_pounds': None},
 {'id': 915,
  'first_name': 'Yinka',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Dare',
  'position': '',
  'team': {'id': 3,
   'abbreviation': 'BKN',
   'city': 'Brooklyn',
   'conference': 'East',
   'division': 'Atlantic',
   'full_name': 'Brooklyn Nets',
   'name': 'Nets'},
  'weight_pounds': None},
 {'id': 46408533,
  'first_name': 'Rod',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Derline',
  'position': '',
  'team': {'id': 21,
   'abbreviation': 'OKC',
   'city': 'Oklahoma City',
   'conference': 'West',
   'division': 'Northwest',
   'full_name': 'Oklahoma City Thunder',
   'name': 'Thunder'},
  'weight_pounds': None},
 {'id': 2830,
  'first_name': 'Terry',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Dozier',
  'position': '',
  'team': {'id': 4,
   'abbreviation': 'CHA',
   'city': 'Charlotte',
   'conference': 'East',
   'division': 'Southeast',
   'full_name': 'Charlotte Hornets',
   'name': 'Hornets'},
  'weight_pounds': None},
 {'id': 2290,
  'first_name': 'John',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Drew',
  'position': '',
  'team': {'id': 1,
   'abbreviation': 'ATL',
   'city': 'Atlanta',
   'conference': 'East',
   'division': 'Southeast',
   'full_name': 'Atlanta Hawks',
   'name': 'Hawks'},
  'weight_pounds': None},
 {'id': 46405958,
  'first_name': 'Ken',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Durrett',
  'position': '',
  'team': {'id': 26,
   'abbreviation': 'SAC',
   'city': 'Sacramento',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'Sacramento Kings',
   'name': 'Kings'},
  'weight_pounds': None},
 {'id': 141,
  'first_name': 'Trevon',
  'height_feet': 6,
  'height_inches': 2,
  'last_name': 'Duval',
  'position': 'G',
  'team': {'id': 17,
   'abbreviation': 'MIL',
   'city': 'Milwaukee',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Milwaukee Bucks',
   'name': 'Bucks'},
  'weight_pounds': 189},
 {'id': 1670,
  'first_name': 'Jordan',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Farmar',
  'position': '',
  'team': {'id': 14,
   'abbreviation': 'LAL',
   'city': 'Los Angeles',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'Los Angeles Lakers',
   'name': 'Lakers'},
  'weight_pounds': None}]

In [52]:
data_ = []
for i in data['data']:
  dict_ = {}
  for key,value in i.items():
    # print(key, value)
    if key != 'team':
      dict_[key] = value
    else:
      for k,v in value.items():
        dict_[f"team_{k}"] = v

  data_.append(dict_)

In [53]:
pd.DataFrame(data_)

,id,first_name,height_feet,height_inches,last_name,position,team_id,team_abbreviation,team_city,team_conference,team_division,team_full_name,team_name,weight_pounds
0,149,Keenan,NaN,NaN,Evans,G,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,NaN
1,382,Billy,NaN,NaN,Preston,F,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,NaN
2,448,Gary,NaN,NaN,Trent Jr.,G,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,NaN
3,46391370,Jake,NaN,NaN,Carter,,50,DN,,,,Denver Nuggets,Denver Nuggets,NaN
4,2144,Rakeem,NaN,NaN,Christmas,,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,NaN
5,46391383,Bill,NaN,NaN,Closs,,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,NaN
6,2714,Kent,NaN,NaN,Edelin,,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,NaN
7,46390214,Don,NaN,NaN,Eliason,,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,NaN
8,46390206,Gorham,NaN,NaN,Getchell,,44,PIT,,,,Pittsburgh Ironmen,Pittsburgh Ironmen,NaN
9,46404351,Gary,NaN,NaN,Gregor,,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,NaN
10,46393997,Jim,NaN,NaN,Holstein,,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,NaN
11,1703,Mile,NaN,NaN,Ilic,,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,NaN
12,2305,Abdul,NaN,NaN,Jeelani,,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,NaN
13,56677845,Colby,NaN,NaN,Jones,G,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,NaN
14,46408537,Steve,NaN,NaN,Jones,,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,NaN
15,38017692,Malaki,NaN,NaN,Branham,F,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,NaN
16,1847,Jon,NaN,NaN,Brockman,,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,NaN
17,38017702,Kennedy,NaN,NaN,Chandler,G,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,NaN
18,915,Yinka,NaN,NaN,Dare,,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,NaN
19,46408533,Rod,NaN,NaN,Derline,,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,NaN
20,2830,Terry,NaN,NaN,Dozier,,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,NaN
21,2290,John,NaN,NaN,Drew,,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,NaN
22,46405958,Ken,NaN,NaN,Durrett,,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,NaN
23,141,Trevon,6.0,2.0,Duval,G,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,189.0
24,1670,Jordan,NaN,NaN,Farmar,,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,NaN